#!/bin/bash

rpm-ostree upgrade

rpm-ostree install \
    calcurse \
    chromium \
    cmus \
    feh \
    git \
    golang \
    gopass \
    grim \
    jq \
    lynx \
    mako \
    mc \
    meld \
    mplayer \
    mutt \
    myrepos \
    newsboat \
    nnn \
    pandoc \
    parallel \
    pinta \
    pmount \
    qalc \
    ripgrep \
    slurp \
    stow \
    sway \
    task \
    tigervnc \
    tmate \
    tmux \
    vim \
    wl-clipboard \
    wofi \
    zathura

flatpak install org.telegram.desktop

echo "You should reboot now"
