#!/bin/bash

rpm-ostree upgrade 

sudo rpm-ostree install \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo rsync -r ./dotfiles/etc/ /etc

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

rsync -r ./dotfiles/home/user/ ~

echo "You should reboot now"
